# TrendRadar 主配置

filter:
  method: "keyword"  # 关键词模式

notification:
  enabled: true
  channels:
    telegram:
      bot_token: "8787275121:AAGq6DOnPM6I6Ow6jyPx4i7RtXSLZJheoEc"
      chat_id: "8548309239"

platforms:
  - zhihu
  - douyin
  - bilibili-hot-search
  - weibo
  - baidu
  - tieba
  - wallstreetcn-hot
  - cls-hot
  - thepaper
  - ifeng
  - toutiao
